---
- hosts: webservers
  become: yes
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    - name: Add nginx configuration for port 8080
      copy:
        dest: /etc/nginx/conf.d/my_site.conf
        content: |
          server {
            listen 8080;
            location / {
              root /usr/share/nginx/html;
              index index.html index.htm;
            }
          }
    - name: Start nginx
      service:
        name: nginx
        state: started
    - name: Copy index.html
      copy:
        src: ../../index.html
        dest: /usr/share/nginx/html/index.html
